Repository xdnathanm/CS312-Project, pull requests merged in 2025-04, with the labels that each got.

#9 Adding About Us PHP file to repo
  angular.json
  package-lock.json
  package.json
  src/app/About.php
Labels: enhancement

#13 Added Pill Link to navigate to About Us page
  package-lock.json
  public/About.php
  src/app/app.component.html
Labels: enhancement

#16 About us page fixed and added my bio
  package-lock.json
  public/About.php
Labels: bug, enhancement

#17 Added the PixelForge image and changed the working title.
  public/PixelForge.jpeg
  src/app/app.component.ts
  src/index.html
Labels: Company home page

#20 Cleaned up le home page and removed all not needed junk
  src/app/app.component.html
  src/app/app.component.spec.ts
Labels: Company home page

#22 Fixed background color to meeet color requirements
  public/About.php
Labels: enhancement

#23 Adding Image to About Us page
  public/About.php
  public/JeffPhoto.jpg
Labels: enhancement

#31 Removing home button and fixing spacing cause I am autistic
  src/app/app.component.html
Labels: enhancement

#35 table 1 functionality(needs color)
  public/Graph.php
Labels: enhancement

#42 Adding button functionality as well as clicking
  public/Graph.php
Labels: enhancement
